# Seris的创建方式

In [2]:
import pandas as pd

# 直接通过Seris类来创建Series对象 直接传入列表 将使用默认索引 从0开始 往后依次+1
s1 = pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
# 指定了索引 可以按照我们指定的索引访问 但仍然可以使用原来的 从0开始的下标访问
s2 = pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'],name="numbers")
s2

a    1
b    2
c    3
d    4
e    5
f    6
Name: numbers, dtype: int64

In [5]:
# 根据字典创建Series对象  键作为索引 值继续保留
dic = {"a" : 1, "b" : -2, "c" : 3, "d" : -4, "e" : 5}
s3 = pd.Series(dic)
s3

a    1
b   -2
c    3
d   -4
e    5
dtype: int64

In [6]:
# 将指定的索引对应的键值对 保留 其他的舍弃  
s4 = pd.Series(dic,index=["a","d","e"],name="numbers")
s4

a    1
d   -4
e    5
Name: numbers, dtype: int64