# Seris的属性

In [1]:
# index 属性
import pandas as pd

s1 = pd.Series([11,22,33,44,55],index=['a','b','c','d','e'],name="numbers")
s1

a    11
b    22
c    33
d    44
e    55
Name: numbers, dtype: int64

In [2]:
# f Field 字段 属性的意思
print(s1.index)

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [3]:
# index属于可迭代对象 所以直接使用for循环遍历
for i in s1.index:
    print(i)

a
b
c
d
e

In [5]:
# values 属性
print(s1.values)
print(type(s1.values))

[11 22 33 44 55]
<class 'numpy.ndarray'>

In [6]:
# ndim 维度
# field 和 property 这两种都可以理解为是类中的属性
# field表示未封装的  property 是封装之后
print(s1.ndim) # Seris是一维的数据结构

1

In [7]:
# 形状
print(s1.shape) # 一列行数据

(5,)

In [8]:
# 元素个数
print(s1.size)

5

In [9]:
# 元素类型
print(s1.dtype)
print(s1.dtypes)

int64
int64

In [10]:
# 名字属性 name
print(s1.name)

numbers

In [12]:
# 按照标签切片 或者 单个元素操作
print(s1.loc["a"])
print(s1.loc["b"])
print(s1.loc["c"])
print(s1.loc["d"])

11
22
33
44

In [13]:
# 切片 根据标签切片 注意：包括起始和结束
s1.loc["a" : "d"]

a    11
b    22
c    33
d    44
Name: numbers, dtype: int64

In [15]:
# 通过iloc 隐式索引 进行切片或者获取单个元素
s1 = pd.Series([11,22,33,44,55],index=['a','b','c','d','e'],name="numbers")

print(s1.iloc[0])
print(s1.iloc[1])
print(s1.iloc[2])
print(s1.iloc[3])

11
22
33
44

In [16]:
# 切片 跟原来规则一致  左闭右开
s1.iloc[0:3]

a    11
b    22
c    33
Name: numbers, dtype: int64

In [17]:
# at 获取单个元素 注意：at不能切片
# at 按照标签获取单个元素
print(s1.at["a"])

11

In [18]:
# iat 按照隐式索引 获取单个元素
print(s1.iat[0])
print(s1.iat[1])

11
22