# DataFrame 的创建

In [1]:
import pandas as pd
# 根据字典创建 指定列和数据
df = pd.DataFrame({
    "id" : [1,2,3,4],
    "name" : ["赵四","广坤","小宝","刘能"],
    "age" : [25,20,30,35]
})
df

   id name  age
0   1   赵四   25
1   2   广坤   20
2   3   小宝   30
3   4   刘能   35

In [3]:
# 根据参数 来指定数据 列 以及 索引
df = pd.DataFrame(
    data={"age" : [22,23,34,45],"name":["赵四","广坤","小宝","刘能"]},
    columns= ["age","name"],
    index = [101,102,103,104]
)
df

     age name
101   22   赵四
102   23   广坤
103   34   小宝
104   45   刘能

In [4]:
df = pd.DataFrame(
    data = {"id" : [101,102,103,104],"name" :["赵四","广坤","小宝","刘能"],"age" :[22,23,34,45] },
    index = ["aa","bb","cc","dd"]
)
df

     id name  age
aa  101   赵四   22
bb  102   广坤   23
cc  103   小宝   34
dd  104   刘能   45

# DataFrame属性

In [5]:
# 行索引
print(df.index)

Index(['aa', 'bb', 'cc', 'dd'], dtype='str')

In [6]:
# 列索引
print(df.columns)

Index(['id', 'name', 'age'], dtype='str')

In [8]:
# 将DataFrame转换为二维的数据
print(df.values)
print(type(df.values))

[[101 '赵四' 22]
 [102 '广坤' 23]
 [103 '小宝' 34]
 [104 '刘能' 45]]
<class 'numpy.ndarray'>

In [9]:
# 维度 ndim
print(df.ndim)

2

In [10]:
# 形状
df = pd.DataFrame(
    data = {"id" : [101,102,103,104],"name" :["赵四","广坤","小宝","刘能"],"age" :[22,23,34,45] },
    index = ["aa","bb","cc","dd"]
)
print(df.shape)

(4, 3)

In [11]:
#元素总个数 行数 * 列数  所有单元格的数量
print(df.size)

12

In [13]:
# 每一列的数据类型
print(df.dtypes)
print(type(df.dtypes)) # 最终的结果还是Series类型的

id      int64
name      str
age     int64
dtype: object
<class 'pandas.Series'>

In [14]:
# 行列转置

print(df.T)

       aa   bb   cc   dd
id    101  102  103  104
name   赵四   广坤   小宝   刘能
age    22   23   34   45

In [18]:
# loc[] 根据标签 获取单个(某一行)或者是切片(多行)操作
df = pd.DataFrame(
    data = {"id" : [101,102,103,104],"name" :["赵四","广坤","小宝","刘能"],"age" :[22,23,34,45] },
    index = ["aa","bb","cc","dd"]
)

# 获取标签为'aa'的这一行数据
df.loc["aa"]

id      101
name     赵四
age      22
Name: aa, dtype: object

In [19]:
df

     id name  age
aa  101   赵四   22
bb  102   广坤   23
cc  103   小宝   34
dd  104   刘能   45

In [20]:
# 切片操作 包含起始和结束

df.loc["aa" : "bb"]

     id name  age
aa  101   赵四   22
bb  102   广坤   23

In [22]:
# 获取所有数据 并且只展示 id 和 name 这两列
df.loc[:,["id","name"]]

     id name
aa  101   赵四
bb  102   广坤
cc  103   小宝
dd  104   刘能

In [23]:
# iloc[] 都是根据数值下标 隐式索引操作的
# 获取第一行数据
df.iloc[0]

id      101
name     赵四
age      22
Name: aa, dtype: object

In [24]:
# 切片获取指定行数据
df.iloc[0:3]

     id name  age
aa  101   赵四   22
bb  102   广坤   23
cc  103   小宝   34

In [26]:
# 切片操作，只要第0(一)列数据
df.iloc[0:3,0]

aa    101
bb    102
cc    103
Name: id, dtype: int64

In [28]:
# at 按照标签索引获取单个数据
# 只能获取单个数据 获取aa这一行的名字数据
df.at["aa","name"]

'赵四'

In [29]:
# 只能获取单个数据 获取aa这一行的id数据
df.at["aa","id"]

np.int64(101)

In [30]:
# 只能获取单个数据 获取aa这一行的年龄数据
df.at["aa","age"]

np.int64(22)

In [31]:
# iat 根据数值索引获取数据 也是只能获取单个的 数据
# 行索引 和 列索引 都是从0开始的
df.iat[0,1]

'赵四'