# DataFrame 常用方法

In [8]:
import pandas as pd

df = pd.DataFrame(
    data = {
        "id" : [101,102,103,104,105,106,101],
        "name" : ["赵四","小宝","富贵","大拿","刘能","张三","赵四"],
        "age" : [10,20,30,40,50,None,10]
    },
    index = ["aa","bb","cc","dd","ee","ff","aa"]
)
df

     id name   age
aa  101   赵四  10.0
bb  102   小宝  20.0
cc  103   富贵  30.0
dd  104   大拿  40.0
ee  105   刘能  50.0
ff  106   张三   NaN
aa  101   赵四  10.0

In [3]:
# head() 默认查看前5行数据
print(df.head())

     id name  age
aa  101   赵四   10
bb  102   小宝   20
cc  103   富贵   30
dd  104   大拿   40
ee  105   刘能   50

In [4]:
print(df.head(3)) # 指定参数查看前3行数据

     id name  age
aa  101   赵四   10
bb  102   小宝   20
cc  103   富贵   30

In [5]:
# tail() 默认查看后5行数据
print(df.tail())

     id name  age
cc  103   富贵   30
dd  104   大拿   40
ee  105   刘能   50
ff  106   张三   60
aa  101   赵四   10

In [6]:
# tail(2) 指定参数查看后2行数据
print(df.tail(2))

     id name  age
ff  106   张三   60
aa  101   赵四   10

In [7]:
# isin() 每个单元格都与集合中的数据进行匹配 查看是否存在
print(df.isin([103, 106]))

       id   name    age
aa  False  False  False
bb  False  False  False
cc   True  False  False
dd  False  False  False
ee  False  False  False
ff   True  False  False
aa  False  False  False

In [9]:
# isna() 判断是否为缺失值 每一个单元格都匹配
df = pd.DataFrame(
    data = {
        "id" : [101,102,103,104,105,106,101],
        "name" : ["赵四","小宝","富贵","大拿","刘能","张三","赵四"],
        "age" : [10,20,30,40,50,None,10]
    },
    index = ["aa","bb","cc","dd","ee","ff","aa"]
)
print(df.isna())

       id   name    age
aa  False  False  False
bb  False  False  False
cc  False  False  False
dd  False  False  False
ee  False  False  False
ff  False  False   True
aa  False  False  False

In [10]:
# sum() 求和 因为DataFrame是一个二维表结构 所以必须指定 要根据那一列求和

df["age"]

aa    10.0
bb    20.0
cc    30.0
dd    40.0
ee    50.0
ff     NaN
aa    10.0
Name: age, dtype: float64

In [11]:
# 将age列求和计算
print(df["age"].sum())

160.0

In [12]:
# 将age列求平均值
print(df["age"].mean())

26.666666666666668

In [13]:
# 将age列求最大值
print(df["age"].max())

50.0

In [14]:
# 将age列求最小值
print(df["age"].min())

10.0

In [15]:
# 统计年龄方差
print(df["age"].var())

266.66666666666663

In [16]:
# 统计年标准差
print(df["age"].std())

16.329931618554518

In [17]:
# 统计年龄中位数
print(df["age"].median())

25.0

In [18]:
# 统计年龄众数
print(df["age"].mode())

0    10.0
Name: age, dtype: float64

In [19]:
# 分位数
print(df["age"].quantile(0.5))

25.0

In [20]:
# 展示当前DataFrame的基本信息
df.info()

<class 'pandas.DataFrame'>
Index: 7 entries, aa to aa
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7 non-null      int64
 1   name    7 non-null      str
 2   age     6 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 524.0+ bytes

In [21]:
# 查看常见的统计指标
# 只会统计数值列 非数值列
print(df.describe())

               id        age
count    7.000000   6.000000
mean   103.142857  26.666667
std      1.951800  16.329932
min    101.000000  10.000000
25%    101.500000  12.500000
50%    103.000000  25.000000
75%    104.500000  37.500000
max    106.000000  50.000000

In [22]:
df = pd.DataFrame(
    data = {
        "id" : [101,102,103,104,105,106,101],
        "name" : ["赵四","小宝","富贵","大拿","刘能","张三","赵四"],
        "age" : [10,20,30,40,50,None,10]
    },
    index = ["aa","bb","cc","dd","ee","ff","aa"]
)
df

     id name   age
aa  101   赵四  10.0
bb  102   小宝  20.0
cc  103   富贵  30.0
dd  104   大拿  40.0
ee  105   刘能  50.0
ff  106   张三   NaN
aa  101   赵四  10.0

In [23]:
# value_counts() 统计每一行数据出现的次数 (整行重复才算  )
print(df.value_counts())

id   name  age
101  赵四    10.0    2
102  小宝    20.0    1
103  富贵    30.0    1
104  大拿    40.0    1
105  刘能    50.0    1
Name: count, dtype: int64

In [24]:
# count() 统计数量 统计每一列 非空数据的数量
print(df.count())

id      7
name    7
age     6
dtype: int64

In [25]:
# drop_duplicates() 去除重复的的元素 只保留第一次出现的
print(df.drop_duplicates())

     id name   age
aa  101   赵四  10.0
bb  102   小宝  20.0
cc  103   富贵  30.0
dd  104   大拿  40.0
ee  105   刘能  50.0
ff  106   张三   NaN

In [26]:
# duplicated() 标记某一行是否是重复行的 (一行的所有列都重复才算 )
print(df.duplicated())

aa    False
bb    False
cc    False
dd    False
ee    False
ff    False
aa     True
dtype: bool

In [28]:
# duplicated()  可以指定列 来单独查看某一列哪些重复内容
df = pd.DataFrame(
    data = {
        "id" : [101,102,103,104,105,106,101],
        "name" : ["赵四","小宝","富贵","大拿","刘能","张三","赵四"],
        "age" : [10,10,30,30,50,None,10]
    },
    index = ["aa","bb","cc","dd","ee","ff","aa"]
)

print(df.duplicated(subset="age"))

aa    False
bb     True
cc    False
dd     True
ee    False
ff    False
aa     True
dtype: bool

In [37]:
# 随机采样 sample() 默认采集一个
print(df.sample())

     id name   age
dd  104   大拿  30.0

In [38]:
# replace() 替换 全表替换
print(df.replace(10, 100))

     id name    age
aa  101   赵四  100.0
bb  102   小宝  100.0
cc  103   富贵   30.0
dd  104   大拿   30.0
ee  105   刘能   50.0
ff  106   张三    NaN
aa  101   赵四  100.0

In [41]:
# equals() 比较两个DataFrame 数据 以及 索引 是否完全一致
df1 = pd.DataFrame(data = {"id" : [101,102,103], "name" : ["赵四","广坤","小宝"],"age" : [10,20,30]})
df2 = pd.DataFrame(data = {"id" : [101,102,103], "name" : ["赵四","广坤","小宝"],"age" : [10,20,30]})

print(df1.equals(df2))

True

In [43]:
# 累计最大值
df = pd.DataFrame({"A" : [2,5,3,7,4],"B" : [1,6,2,8,3]})
print(df)

   A  B
0  2  1
1  5  6
2  3  2
3  7  8
4  4  3

In [44]:
# 累计最大值 cummax() 纵向
print(df.cummax())

   A  B
0  2  1
1  5  6
2  5  6
3  7  8
4  7  8

In [45]:
# 累计最大值 cummax() 纵向
print(df.cummax(axis=0))

   A  B
0  2  1
1  5  6
2  5  6
3  7  8
4  7  8

In [46]:
# 横向
print(df.cummax(axis=1))

   A  B
0  2  2
1  5  6
2  3  3
3  7  8
4  4  4

In [47]:
print(df.cummax(axis="index")) # 纵向

   A  B
0  2  1
1  5  6
2  5  6
3  7  8
4  7  8

In [48]:
print(df.cummax(axis="columns")) # 横向

   A  B
0  2  2
1  5  6
2  3  3
3  7  8
4  4  4

In [49]:
df = pd.DataFrame({"A" : [2,5,3,7,4],"B" : [1,6,2,8,3]})
print(df.cummin())

   A  B
0  2  1
1  2  1
2  2  1
3  2  1
4  2  1

In [50]:
print(df.cummin(axis=0)) # 纵向

   A  B
0  2  1
1  2  1
2  2  1
3  2  1
4  2  1

In [51]:
print(df.cummin(axis=1)) # 横向

   A  B
0  2  1
1  5  5
2  3  2
3  7  7
4  4  3

In [52]:
# 累计求和  cumsum()
print(df.cumsum())

    A   B
0   2   1
1   7   7
2  10   9
3  17  17
4  21  20

In [53]:
print(df.cumsum(axis=0))

    A   B
0   2   1
1   7   7
2  10   9
3  17  17
4  21  20

In [54]:
print(df.cumsum(axis=1))

   A   B
0  2   3
1  5  11
2  3   5
3  7  15
4  4   7