# Series常用方法

In [2]:
# head() 查看前5条数据
import pandas as pd
import numpy as np

s1 = pd.Series([11,22,np.nan,44,33,None,22],index=["a","b","c","d","e","f","g"])
s1.head()

a    11.0
b    22.0
c     NaN
d    44.0
e    33.0
dtype: float64

In [3]:
# head(3) 查看前3条数据
s1.head(3)

a    11.0
b    22.0
c     NaN
dtype: float64

In [4]:
# tail() 默认为查看后边的5条数据
s1.tail()

c     NaN
d    44.0
e    33.0
f     NaN
g    22.0
dtype: float64

In [5]:
# tail(2) 查看后2条数据
s1.tail(2)

f     NaN
g    22.0
dtype: float64

In [7]:
# isin([集合]) 判断Series中的每一个元素 是否存在于指定的集合中
s1 = pd.Series([11,22,np.nan,44,33,None,22],index=["a","b","c","d","e","f","g"])
print(s1.isin([11,22]))

a     True
b     True
c    False
d    False
e    False
f    False
g     True
dtype: bool

In [8]:
# isna() 判断Series对象中的每一个元素 是否为缺失值 np.nan None 都属于缺失值
s1 = pd.Series([11,22,np.nan,44,33,None,22],index=["a","b","c","d","e","f","g"])
s1.isna()

a    False
b    False
c     True
d    False
e    False
f     True
g    False
dtype: bool

In [9]:
# sum() 求和 缺失值不计算在内  忽略
print(s1.sum())

132.0

In [10]:
# 平均值
print(s1.mean())

26.4

In [11]:
# 最大值 和 最小值
print(s1.max())
print(s1.min())

44.0
11.0

In [13]:
# 方差和标准差
print("方差",s1.var())
print("标准差",s1.std())

157.3
12.541929676090518

In [15]:
# 中位数 会先自动排序
# 元素奇数，中间那个数值
# 元素偶数，中间的两个数值求个 / 2
print(s1.median())

22.0

In [16]:
# 众数 出现次数最多的数据
s1 = pd.Series([11,22,np.nan,44,33,None,22],index=["a","b","c","d","e","f","g"])

print(s1.mode())

0    22.0
dtype: float64

In [18]:
s2 = pd.Series([1,1,1,2,2,2,2,3,3])
print(s2.mode())

0    2
dtype: int64

In [19]:
# 分位数
# 先对序列进行排序
# index = (n - 1) * q
# index = 1
s1 = pd.Series([11,22,np.nan,44,33,None,22],index=["a","b","c","d","e","f","g"])

print(s1.quantile(0.25))

22.0

In [20]:
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
# index = (n - 1) * q
# index = (4 - 1) * 0.25
# index = 0.75 如果获取到的下标不是整数 则默认按照差值 * 分位的方式 计算 + (之前的累计值)
print(s1.quantile(0.25))

19.25

In [21]:
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
# index = (4 - 1) * 0.25
# index = 0.75 如果获取到的下标不是整数 则默认按照差值 * 分位的方式 计算 + (之前的累计值)
print(s1.quantile(0.25,interpolation="nearest")) # 使用离其最近的值

22.0

In [22]:
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
# index = (4 - 1) * 0.25
# index = 0.75 如果获取到的下标不是整数 则默认按照差值 * 分位的方式 计算 + (之前的累计值)
print(s1.quantile(0.25,interpolation="midpoint")) # 使用中间值

16.5

In [23]:
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
# index = (4 - 1) * 0.25
# index = 0.75 如果获取到的下标不是整数 则默认按照差值 * 分位的方式 计算 + (之前的累计值)
print(s1.quantile(0.25,interpolation="lower")) # 使用左边的最小值

11.0

In [24]:
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
# index = (4 - 1) * 0.25
# index = 0.75 如果获取到的下标不是整数 则默认按照差值 * 分位的方式 计算 + (之前的累计值)
print(s1.quantile(0.25,interpolation="higher")) # 使用右边的最大值

22.0

In [25]:
# describe 输出常用的统计信息 总个数 均值 标准差 最大值 最小值 分位数
print(s1.describe())

count     4.000000
mean     24.750000
std      13.841363
min      11.000000
25%      19.250000
50%      22.000000
75%      27.500000
max      44.000000
dtype: float64

In [26]:
# value_counts() 统计每个值出现了多少次 缺失值不统计
print(s1.value_counts())

22.0    2
11.0    1
44.0    1
Name: count, dtype: int64

In [27]:
# count() 统计总的元素个数 缺失值不计算在内
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","b","c","d","e","f"])
print(s1.count())

4

In [28]:
# 查看所有元素的个数
print(len(s1))

6

In [29]:
# drop_duplicates() 去除重复 只保留第一次出现的值  并且排序

print(s1.drop_duplicates())

a    11.0
b    22.0
c     NaN
d    44.0
dtype: float64

In [30]:
# unique() 获取去重之后的所有值 返回的是一个ndarray数组  不保留索引
arr1 = s1.unique()
print(arr1)
print(type(arr1))

[11. 22. nan 44.]
<class 'numpy.ndarray'>

In [31]:
# nunique() 统计去除重复之后 非缺失值的个数
print(s1.nunique())

3

In [42]:
# 随机采样  sample() 随机取一个数据
print(s1.sample())

e   NaN
dtype: float64

In [45]:
# 随机采样  sample() 可以指定随机取多少数据
print(s1.sample(2))

d    44.0
b    22.0
dtype: float64

In [46]:
# sort_index() 按照索引排序
s1 = pd.Series([11,22,np.nan,44,None,22],index=["a","c","b","e","d","f"])
print(s1.sort_index())

a    11.0
b     NaN
c    22.0
d     NaN
e    44.0
f    22.0
dtype: float64

In [47]:
# 按照值排序
# sort_values()
# 缺失值排在最后
print(s1.sort_values())

a    11.0
c    22.0
f    22.0
e    44.0
b     NaN
d     NaN
dtype: float64

In [48]:
# 替换 replace() 将22替换为abc
print(s1.replace(22, "abc"))

a    11.0
c     abc
b     NaN
e    44.0
d     NaN
f     abc
dtype: object

In [50]:
# 内容相同 索引也相同 为True
s2 = pd.Series([1,2,3])
s3 = pd.Series([1,2,3])

print(s2)
print(s3)
print(s2.equals(s3))

0    1
1    2
2    3
dtype: int64
0    1
1    2
2    3
dtype: int64
True

In [51]:
# 内容相同 索引不相同 为False
s2 = pd.Series([1,2,3],index=["a","b","c"])
s3 = pd.Series([1,2,3])

print(s2)
print(s3)
print(s2.equals(s3))

a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
dtype: int64
False

In [52]:
# keys() 和 属性 index 效果相同 都用于获取索引(标签)
s2 = pd.Series([1,2,3],index=["a","b","c"])
print(s2.index)
print(s2.keys())

Index(['a', 'b', 'c'], dtype='str')
Index(['a', 'b', 'c'], dtype='str')